"use strict";
exports.__esModule = true;
var Animal_1 = require("./Animal");
var Mammal_1 = require("./Mammal");
var Reptile_1 = require("./Reptile");
var Canine_1 = require("./Canine");
var Feline_1 = require("./Feline");
var Cat_1 = require("./Cat");
var Dog_1 = require("./Dog");
console.log("WELCOME");
var animal = new Animal_1.Animal("Earth");
console.log(animal.show());
console.log("\n-------------------------");
var reptile = new Reptile_1.Reptile("Water");
var mammal = new Mammal_1.Mammal("Earth");
console.log(mammal.show());
console.log("\n-------------------------");
var canine = new Canine_1.Canine("garden", "golden retriever");
var dog = new Dog_1.Dog("garden", "golden retriever", "woof woof");
console.log(dog.talk());
console.log("\n-------------------------");
var feline = new Feline_1.Feline("garden", "persa idk");
var cat = new Cat_1.Cat("garden", "golden retriever", "meow meow", "Fisga");
console.log(cat.talk());
